[package]
name = "rust_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.4.0"
stopwatch = "0.0.7"
strum = "0.24.1"
strum_macros = "0.24.1"
